"""Rule-based guided TeachBack conversation.

The session walks through a topic's required concepts one short question at a
time, like a friendly tutor. All behaviour is deterministic: the NLP analyzer
provides evidence (concept similarities, misconceptions), and fixed rules
decide the feedback and the next question. No text is generated by an LLM.

Per turn:
  1. Misconception detected            -> explain the distinction, probe it once.
  2. Answer clearly demonstrates the   -> encourage, move to the next concept
     concept                              (skipping any covered incidentally).
  3. Answer is partially right         -> one targeted probe, then accept.
  4. Answer is unclear / very short    -> one easier question, then move on.
A misconception probed once and no longer detected in the reply is marked
resolved. The session ends when every concept has been visited (plus an
optional extension question when everything went well), or at MAX_QUESTIONS.
"""

# Targeted thresholds are a little more permissive than the analyzer's global
# ones: the question already establishes the context, so a short on-point
# answer ("It tells us how the loss changes") should count. The contextual
# score (concept name prefixed to the answer) is only trusted when the answer
# shares at least one content word with the concept text — the shared prefix
# otherwise inflates similarity for any text, including "I don't know".
TARGET_COVERED_T = 0.58
TARGET_PARTIAL_T = 0.45
CTX_COVERED_T = 0.66
CTX_PARTIAL_T = 0.58
MIN_WORDS = 3
MAX_QUESTIONS = 12

GIVE_UP_PHRASES = ("i don't know", "i dont know", "idk", "no idea", "not sure", "no clue")

ACK_CORRECT = [
    "Exactly.",
    "Good — that's right.",
    "Right.",
    "Nicely put.",
    "That's it.",
]
ACK_PARTIAL = [
    "You're on the right track.",
    "Almost — you have part of it.",
    "That's partly right.",
    "Good start — let's go one step further.",
]
ACK_UNCLEAR = [
    "No problem — let's take a smaller step.",
    "That's okay — let's try it from an easier angle.",
    "Let's simplify it a little.",
]
ACK_ACCEPT_PARTIAL = [
    "Good enough — you have the main idea. Let's move on.",
    "Okay, you've got the core of it. Let's keep going.",
]
ACK_MOVE_ON = [
    "That's alright — we'll come back to this one. Let's move on.",
    "Okay, let's leave that for now and continue.",
]
ACK_RESOLVED = [
    "That's it — you've cleared that up.",
    "Exactly — that distinction is clear now.",
]

GENERIC_MAIN = "In one or two sentences, what is \"{concept}\" about?"
GENERIC_EASIER = "Let's make it simpler: how would you describe \"{concept}\" to a friend?"
GENERIC_PROBE = "Can you say a bit more about how \"{concept}\" fits into {topic}?"
CLOSING = "That completes our conversation about {topic}. Before we finish, tell me how this session felt."


def _pick(options: list[str], n: int) -> str:
    return options[n % len(options)]


def build_plan(topic_def: dict) -> dict:
    """Initial conversation state, stored on the session between requests."""
    return {
        "concepts": [
            {"id": c.get("id"), "name": c["name"], "status": "pending", "attempts": 0}
            for c in topic_def.get("concepts", [])
        ],
        "current": 0,
        "question_no": 1,
        "asked_kind": "main",
        "asked_miscon": None,
        "miscon_seen": [],
        "resolved": [],
        "detected": [],
        "extension_asked": False,
        "done": False,
    }


def question_for(concept_def: dict, kind: str, topic_name: str) -> str:
    key = {"main": "main_question", "easier": "easier_question", "probe": "probe_question"}[kind]
    generic = {"main": GENERIC_MAIN, "easier": GENERIC_EASIER, "probe": GENERIC_PROBE}[kind]
    return concept_def.get(key) or generic.format(concept=concept_def["name"], topic=topic_name)


def first_question(plan: dict, topic_def: dict) -> dict:
    concept = topic_def["concepts"][0] if topic_def.get("concepts") else None
    if concept is None:
        return {"kind": "open", "text": topic_def.get("opening_prompt") or "Teach me this topic in your own words.",
                "concept": None, "reason": "This topic has no structured concepts, so the open prompt is used."}
    return {
        "kind": "main",
        "text": question_for(concept, "main", topic_def.get("name", "this topic")),
        "concept": concept["name"],
        "reason": "Opening question for the first concept.",
    }


def _concept_def(topic_def: dict, entry: dict) -> dict:
    for c in topic_def.get("concepts", []):
        if (entry.get("id") is not None and c.get("id") == entry["id"]) or c["name"] == entry["name"]:
            return c
    return {"name": entry["name"]}


def _similarity_for(analysis: dict, entry: dict) -> float:
    for c in analysis.get("concepts", []):
        if (entry.get("id") is not None and c.get("id") == entry["id"]) or c["name"] == entry["name"]:
            return float(c.get("similarity", 0.0))
    return 0.0


def _verdict(analysis: dict, entry: dict) -> str:
    """Judge the answer against the concept currently being asked about."""
    words = analysis.get("word_count", 0)
    text = " ".join(analysis.get("sentences", [])).lower()
    gave_up = words < 8 and any(p in text for p in GIVE_UP_PHRASES)
    if words < MIN_WORDS or gave_up:
        return "unclear"

    tc = analysis.get("target_check") or {}
    plain = max(_similarity_for(analysis, entry), tc.get("plain", 0.0))
    ctx = tc.get("contextual", 0.0)
    overlap = tc.get("overlap", 0)

    if plain >= TARGET_COVERED_T or (ctx >= CTX_COVERED_T and overlap >= 1):
        return "correct"
    if plain >= TARGET_PARTIAL_T or (ctx >= CTX_PARTIAL_T and overlap >= 1):
        return "partial"
    return "unclear"


def _mark_incidental(plan: dict, analysis: dict) -> list[str]:
    """Concepts clearly demonstrated in passing (not the one being asked).

    Pending concepts get skipped later (and reported so the student knows);
    concepts previously marked partial/unclear are upgraded silently.
    """
    newly = []
    for i, entry in enumerate(plan["concepts"]):
        if i == plan["current"] or entry["status"] not in ("pending", "partial", "unclear"):
            continue
        for c in analysis.get("concepts", []):
            same = (entry.get("id") is not None and c.get("id") == entry["id"]) or c["name"] == entry["name"]
            if same and c["status"] == "covered":
                if entry["status"] == "pending":
                    newly.append(entry["name"])
                entry["status"] = "covered"
    return newly


def _advance(plan: dict, topic_def: dict, feedback: str) -> dict:
    """Move to the next pending concept, or the extension question, or finish."""
    topic_name = topic_def.get("name", "this topic")
    for i, entry in enumerate(plan["concepts"]):
        if entry["status"] == "pending":
            plan["current"] = i
            plan["asked_kind"] = "main"
            plan["asked_miscon"] = None
            plan["question_no"] += 1
            cdef = _concept_def(topic_def, entry)
            return {
                "feedback": feedback,
                "followup": {
                    "kind": "main",
                    "text": question_for(cdef, "main", topic_name),
                    "concept": entry["name"],
                    "reason": f"Moving on to the next concept: {entry['name']}.",
                },
                "done": False,
            }

    all_good = all(e["status"] == "covered" for e in plan["concepts"]) and not plan["detected"]
    extension = topic_def.get("extension_question", "")
    if all_good and extension and not plan["extension_asked"] and plan["question_no"] < MAX_QUESTIONS:
        plan["extension_asked"] = True
        plan["asked_kind"] = "extension"
        plan["asked_miscon"] = None
        plan["question_no"] += 1
        return {
            "feedback": feedback,
            "followup": {
                "kind": "extension",
                "text": extension,
                "concept": None,
                "reason": "Every concept was demonstrated, so here is one stretch question.",
            },
            "done": False,
        }

    plan["done"] = True
    return {"feedback": feedback, "followup": None, "done": True,
            "closing": CLOSING.format(topic=topic_name)}


def play_turn(plan: dict, analysis: dict, topic_def: dict) -> tuple[dict, dict]:
    """Process one student answer. Returns (updated plan, turn result).

    The result dict contains: feedback, followup (None when the questioning is
    over), done, and optionally misconception {name, clarification},
    resolved_misconception, incidental (concept names covered in passing),
    closing.
    """
    plan = {**plan, "concepts": [dict(c) for c in plan["concepts"]],
            "miscon_seen": list(plan["miscon_seen"]), "resolved": list(plan["resolved"]),
            "detected": list(plan["detected"])}
    topic_name = topic_def.get("name", "this topic")
    qn = plan["question_no"]
    extras: dict = {}

    # Topic without structured concepts: accept one open explanation and close.
    if not plan["concepts"]:
        plan["done"] = True
        return plan, {"feedback": "Thanks for explaining that.", "followup": None,
                      "done": True, "closing": CLOSING.format(topic=topic_name)}

    incidental = _mark_incidental(plan, analysis)
    if incidental:
        extras["incidental"] = incidental

    # Hard stop: never exceed the question budget.
    if plan["question_no"] >= MAX_QUESTIONS:
        plan["done"] = True
        result = {"feedback": "Thanks — that gives me a good picture.", "followup": None,
                  "done": True, "closing": CLOSING.format(topic=topic_name), **extras}
        return plan, result

    # --- answering a misconception probe ---
    if plan["asked_kind"] == "misconception" and plan["asked_miscon"]:
        name = plan["asked_miscon"]
        still_detected = name in analysis.get("detected_misconceptions", [])
        cur = plan["concepts"][plan["current"]]
        if not still_detected:
            plan["resolved"].append(name)
            extras["resolved_misconception"] = name
            # credit the current concept from this answer too; explaining the
            # distinction correctly earns at least partial credit
            cur["status"] = "covered" if _verdict(analysis, cur) == "correct" else "partial"
            result = _advance(plan, topic_def, _pick(ACK_RESOLVED, qn))
            return plan, {**result, **extras}
        # still confused: leave the misconception recorded, mark the concept unclear, move on
        cur["status"] = "unclear"
        miscon = next((m for m in topic_def.get("misconceptions", []) if m["name"] == name), None)
        clar = (miscon or {}).get("clarification", "")
        feedback = ("We'll come back to this — for now, keep in mind: " + clar) if clar else \
            "We'll come back to this one later."
        result = _advance(plan, topic_def, feedback)
        return plan, {**result, **extras}

    # --- answering the extension question: no status changes, just close ---
    if plan["asked_kind"] == "extension":
        good = analysis["features"].get("semantic_correctness", 0) >= 0.5
        feedback = "Great answer to a hard question." if good else "Good attempt — that one goes beyond the basics."
        plan["done"] = True
        return plan, {"feedback": feedback, "followup": None, "done": True,
                      "closing": CLOSING.format(topic=topic_name), **extras}

    # --- new misconception detected in a normal answer ---
    fresh = [m for m in analysis.get("misconceptions", [])
             if m.get("detected") and m["name"] not in plan["miscon_seen"]]
    if fresh:
        worst = max(fresh, key=lambda m: m.get("similarity", 0))
        name = worst["name"]
        plan["miscon_seen"].append(name)
        if name not in plan["detected"]:
            plan["detected"].append(name)
        full = next((m for m in topic_def.get("misconceptions", []) if m["name"] == name), {})
        clarification = full.get("clarification", "")
        probe = full.get("probe_question") or "Can you explain that again in your own words?"
        plan["asked_kind"] = "misconception"
        plan["asked_miscon"] = name
        plan["question_no"] += 1
        feedback = "Let's separate two ideas here. " + clarification if clarification else \
            "Let's look at that idea more carefully."
        return plan, {
            "feedback": feedback,
            "followup": {"kind": "misconception", "text": probe, "concept": plan["concepts"][plan["current"]]["name"],
                         "reason": f"A common misconception (\"{name}\") appeared in the answer."},
            "misconception": {"name": name, "clarification": clarification},
            "done": False,
            **extras,
        }

    # --- evaluate the current concept ---
    cur = plan["concepts"][plan["current"]]
    cdef = _concept_def(topic_def, cur)
    verdict = _verdict(analysis, cur)

    if verdict == "correct":
        cur["status"] = "covered"
        result = _advance(plan, topic_def, _pick(ACK_CORRECT, qn))
        return plan, {**result, **extras}

    if verdict == "partial":
        if cur["attempts"] == 0:
            cur["attempts"] = 1
            plan["asked_kind"] = "probe"
            plan["question_no"] += 1
            return plan, {
                "feedback": _pick(ACK_PARTIAL, qn),
                "followup": {"kind": "probe", "text": question_for(cdef, "probe", topic_name),
                             "concept": cur["name"],
                             "reason": "The answer was partly right, so a targeted follow-up digs one level deeper."},
                "done": False,
                **extras,
            }
        cur["status"] = "partial"
        result = _advance(plan, topic_def, _pick(ACK_ACCEPT_PARTIAL, qn))
        return plan, {**result, **extras}

    # unclear
    if cur["attempts"] == 0:
        cur["attempts"] = 1
        plan["asked_kind"] = "easier"
        plan["question_no"] += 1
        return plan, {
            "feedback": _pick(ACK_UNCLEAR, qn),
            "followup": {"kind": "easier", "text": question_for(cdef, "easier", topic_name),
                         "concept": cur["name"],
                         "reason": "The answer was hard to interpret, so an easier question is asked."},
            "done": False,
            **extras,
        }
    cur["status"] = "unclear"
    result = _advance(plan, topic_def, _pick(ACK_MOVE_ON, qn))
    return plan, {**result, **extras}


def timeline_out(plan: dict) -> list[dict]:
    """Concept timeline for the UI: done / clarify / current / pending."""
    out = []
    for i, entry in enumerate(plan["concepts"]):
        if entry["status"] == "covered":
            display = "done"
        elif entry["status"] in ("partial", "unclear"):
            display = "clarify"
        elif i == plan["current"] and not plan["done"]:
            display = "current"
        else:
            display = "pending"
        out.append({"name": entry["name"], "status": display})
    return out
