"""Rule-based guided TeachBack conversation.

The session walks through a topic's required concepts one short question at a
time, like a friendly tutor. All behaviour is deterministic: the NLP analyzer
provides evidence (concept similarities, misconceptions), and fixed rules
decide the feedback and the next question. No text is generated by an LLM.

Per turn:
  1. Misconception detected            -> explain the distinction, probe it once.
  2. Answer clearly demonstrates the   -> encourage, move to the next concept
     concept                              (skipping any covered incidentally).
  3. Answer is partially right         -> one targeted probe, then accept.
  4. Short confirmation ("yes") of a   -> positive evidence, not full credit:
     yes/no-style question                ask for the idea in their own words.
  5. Answer is unclear / very short    -> one easier question, then move on.
A misconception probed once and no longer detected in the reply is marked
resolved. The session ends when every concept has been visited (plus an
optional extension question when everything went well), or at MAX_QUESTIONS.
"""
import re

# Targeted thresholds are a little more permissive than the analyzer's global
# ones: the question already establishes the context, so a short on-point
# answer ("It tells us how the loss changes") should count. The contextual
# score (concept name prefixed to the answer) is only trusted when the answer
# shares at least one content word with the concept text — the shared prefix
# otherwise inflates similarity for any text, including "I don't know".
# Calibrated against the labelled dataset in data/nlp/labeled_answers.json
# (python scripts/evaluate_nlp.py --tune): these values maximised evidence-
# level accuracy (0.83) without hurting misconception precision (1.0).
TARGET_COVERED_T = 0.54
TARGET_PARTIAL_T = 0.42
CTX_COVERED_T = 0.62
CTX_PARTIAL_T = 0.55
MIN_WORDS = 2  # a two-word answer ("Text data.") can still be real evidence
MAX_QUESTIONS = 12
MAX_REL_QUESTIONS = 2  # at most this many relationship questions per session

GIVE_UP_PHRASES = ("i don't know", "i dont know", "idk", "no idea", "not sure", "no clue")

# Markers of an analogy/metaphor answer. An analogy that is semantically in
# the neighbourhood of the concept is treated as potentially meaningful
# evidence: instead of rejecting it (no shared words) or blindly accepting it,
# the tutor asks the student to connect it back to the concept.
ANALOGY_MARKERS = ("it's like", "its like", "is like", "kind of like", "sort of like",
                   "as if", "imagine", "think of it as", "similar to", "just like")
ANALOGY_MIN_PLAIN = 0.38
ANALOGY_MIN_CTX = 0.50

# A short confirmation of a yes/no-style question ("Does the gradient tell us
# how the loss changes?" -> "yes") is positive evidence, but not enough for
# full credit — the tutor asks for the idea in the student's own words.
AFFIRMATION_PHRASES = {
    "yes", "yeah", "yep", "yup", "ya", "correct", "right", "exactly", "true",
    "i think so", "i agree", "that's right", "thats right", "definitely", "absolutely",
}
CONFIRM_STARTERS = ("does", "do", "is", "are", "can", "could", "would",
                    "did", "has", "have", "was", "were", "will", "should")


def _is_affirmation(text: str) -> bool:
    norm = re.sub(r"[^a-z' ]", "", text.lower()).strip()
    words = norm.split()
    return norm in AFFIRMATION_PHRASES or (words[:1] == ["yes"] and len(words) <= 4)


def _invites_confirmation(question: str) -> bool:
    """True for yes/no-phrased questions, where a bare "yes" is meaningful."""
    first = question.strip().lower().split(" ", 1)[0].rstrip(",:;") if question.strip() else ""
    return first in CONFIRM_STARTERS

ACK_CORRECT = [
    "Exactly.",
    "Good — that's right.",
    "Right.",
    "Nicely put.",
    "That's it.",
]
ACK_PARTIAL = [
    "You're on the right track.",
    "Almost — you have part of it.",
    "That's partly right.",
    "Good start — let's go one step further.",
]
ACK_UNCLEAR = [
    "No problem — let's take a smaller step.",
    "That's okay — let's try it from an easier angle.",
    "Let's simplify it a little.",
]
ACK_ACCEPT_PARTIAL = [
    "Good enough — you have the main idea. Let's move on.",
    "Okay, you've got the core of it. Let's keep going.",
]
ACK_MOVE_ON = [
    "That's alright — we'll come back to this one. Let's move on.",
    "Okay, let's leave that for now and continue.",
]
ACK_RESOLVED = [
    "That's it — you've cleared that up.",
    "Exactly — that distinction is clear now.",
]
ACK_AFFIRM = [
    "Yes — that's the right idea.",
    "Right — good.",
]
ACK_AFFIRM_ACCEPT = "Okay — you agree with the idea; we'll firm it up with practice. Let's move on."

DEEPEN_QUESTION = "Can you explain what that means in your own words?"
GENERIC_MAIN = "In one or two sentences, what is \"{concept}\" about?"
GENERIC_EASIER = "Let's make it simpler: how would you describe \"{concept}\" to a friend?"
GENERIC_PROBE = "Can you say a bit more about how \"{concept}\" fits into {topic}?"
CLOSING = "That completes our conversation about {topic}. Before we finish, tell me how this session felt."


def _pick(options: list[str], n: int) -> str:
    return options[n % len(options)]


def build_plan(topic_def: dict) -> dict:
    """Initial conversation state, stored on the session between requests."""
    return {
        "concepts": [
            {"id": c.get("id"), "name": c["name"], "status": "pending", "attempts": 0}
            for c in topic_def.get("concepts", [])
        ],
        "relationships": [
            {"id": r.get("id"), "source": r["source"], "label": r.get("label", "relates to"),
             "target": r["target"], "status": "pending", "asked": False}
            for r in topic_def.get("relationships", [])
        ],
        "current": 0,
        "question_no": 1,
        "asked_kind": "main",
        "asked_miscon": None,
        "asked_rel": None,
        "rel_questions": 0,
        "miscon_seen": [],
        "resolved": [],
        "detected": [],
        "extension_asked": False,
        "done": False,
    }


def question_for(concept_def: dict, kind: str, topic_name: str) -> str:
    key = {"main": "main_question", "easier": "easier_question", "probe": "probe_question"}[kind]
    generic = {"main": GENERIC_MAIN, "easier": GENERIC_EASIER, "probe": GENERIC_PROBE}[kind]
    return concept_def.get(key) or generic.format(concept=concept_def["name"], topic=topic_name)


def first_question(plan: dict, topic_def: dict) -> dict:
    concept = topic_def["concepts"][0] if topic_def.get("concepts") else None
    if concept is None:
        return {"kind": "open", "text": topic_def.get("opening_prompt") or "Teach me this topic in your own words.",
                "concept": None, "reason": "This topic has no structured concepts, so the open prompt is used."}
    return {
        "kind": "main",
        "text": question_for(concept, "main", topic_def.get("name", "this topic")),
        "concept": concept["name"],
        "reason": "Opening question for the first concept.",
    }


def _concept_def(topic_def: dict, entry: dict) -> dict:
    for c in topic_def.get("concepts", []):
        if (entry.get("id") is not None and c.get("id") == entry["id"]) or c["name"] == entry["name"]:
            return c
    return {"name": entry["name"]}


def _similarity_for(analysis: dict, entry: dict) -> float:
    for c in analysis.get("concepts", []):
        if (entry.get("id") is not None and c.get("id") == entry["id"]) or c["name"] == entry["name"]:
            return float(c.get("similarity", 0.0))
    return 0.0


def _verdict(analysis: dict, entry: dict, confirm_context: bool = False) -> str:
    """Judge the answer against the concept currently being asked about.

    confirm_context: the question just asked was yes/no-phrased, so a short
    confirmation ("yes") is positive evidence — returned as "affirm" — rather
    than an unclear answer. It is never full credit by itself.
    """
    words = analysis.get("word_count", 0)
    text = " ".join(analysis.get("sentences", [])).lower()
    gave_up = words < 8 and any(p in text for p in GIVE_UP_PHRASES)
    if confirm_context and not gave_up and _is_affirmation(text):
        return "affirm"
    if words < MIN_WORDS or gave_up:
        return "unclear"

    tc = analysis.get("target_check") or {}
    plain = max(_similarity_for(analysis, entry), tc.get("plain", 0.0))
    ctx = tc.get("contextual", 0.0)
    overlap = tc.get("overlap", 0)

    if plain >= TARGET_COVERED_T or (ctx >= CTX_COVERED_T and overlap >= 1):
        return "correct"
    if plain >= TARGET_PARTIAL_T or (ctx >= CTX_PARTIAL_T and overlap >= 1):
        return "partial"
    # an analogy in the neighbourhood of the concept: not credit, not a
    # rejection — the tutor will ask the student to connect it back
    if any(p in text for p in ANALOGY_MARKERS) and (
            plain >= ANALOGY_MIN_PLAIN or ctx >= ANALOGY_MIN_CTX):
        return "analogy"
    return "unclear"


def _mark_incidental(plan: dict, analysis: dict) -> list[str]:
    """Concepts clearly demonstrated in passing (not the one being asked).

    Pending concepts get skipped later (and reported so the student knows);
    concepts previously marked partial/unclear are upgraded silently.
    """
    newly = []
    for i, entry in enumerate(plan["concepts"]):
        if i == plan["current"] or entry["status"] not in ("pending", "partial", "unclear"):
            continue
        for c in analysis.get("concepts", []):
            same = (entry.get("id") is not None and c.get("id") == entry["id"]) or c["name"] == entry["name"]
            if same and c["status"] == "covered":
                if entry["status"] == "pending":
                    newly.append(entry["name"])
                entry["status"] = "covered"
    return newly


def _relationship_result(analysis: dict, entry: dict) -> dict | None:
    """The analyzer's verdict for one relationship of the conversation plan."""
    for res in analysis.get("relationships", []):
        if (entry.get("id") is not None and res.get("id") == entry["id"]) or (
            res["source"] == entry["source"] and res["target"] == entry["target"]
        ):
            return res
    return None


def _update_relationships(plan: dict, analysis: dict) -> None:
    """Accumulate relationship evidence across the whole session.

    Only two verdicts move a relationship here: evidence FOR the connection and
    evidence AGAINST it. "partial" (the answer brushed past the connection) and
    "not_shown" leave the relationship pending, because an answer that happens
    to be near a connection the student was never asked about is not evidence
    that they misunderstand it. Evidence only improves: a relationship once
    demonstrated stays demonstrated.
    """
    by_key = {(r.get("id"), r["source"], r["target"]): r for r in plan.get("relationships", [])}
    for res in analysis.get("relationships", []):
        entry = by_key.get((res.get("id"), res["source"], res["target"]))
        if entry is None:
            continue
        if res["status"] == "demonstrated":
            entry["status"] = "demonstrated"
        elif res["status"] == "contradicted" and entry["status"] != "demonstrated":
            entry["status"] = "contradicted"


def _rel_def(topic_def: dict, entry: dict) -> dict:
    for r in topic_def.get("relationships", []):
        if (entry.get("id") is not None and r.get("id") == entry["id"]) or (
            r["source"] == entry["source"] and r["target"] == entry["target"]
        ):
            return r
    return entry


GENERIC_REL_QUESTION = "You've got {source}. How does it relate to {target}?"


def _advance(plan: dict, topic_def: dict, feedback: str) -> dict:
    """Move to the next pending concept, then probe relationship gaps, then
    the extension question, then finish."""
    topic_name = topic_def.get("name", "this topic")
    for i, entry in enumerate(plan["concepts"]):
        if entry["status"] == "pending":
            plan["current"] = i
            plan["asked_kind"] = "main"
            plan["asked_miscon"] = None
            plan["question_no"] += 1
            cdef = _concept_def(topic_def, entry)
            return {
                "feedback": feedback,
                "followup": {
                    "kind": "main",
                    "text": question_for(cdef, "main", topic_name),
                    "concept": entry["name"],
                    "reason": f"Moving on to the next concept: {entry['name']}.",
                },
                "done": False,
            }

    # every concept visited -> probe the most important relationship gaps
    # (contradicted connections first, then ones not yet demonstrated)
    if plan["rel_questions"] < MAX_REL_QUESTIONS and plan["question_no"] < MAX_QUESTIONS:
        candidates = sorted(
            (r for r in plan.get("relationships", [])
             if not r["asked"] and r["status"] in ("contradicted", "pending")),
            key=lambda r: 0 if r["status"] == "contradicted" else 1,
        )
        if candidates:
            rel = candidates[0]
            rel["asked"] = True
            plan["rel_questions"] += 1
            plan["asked_kind"] = "relationship"
            plan["asked_rel"] = [rel.get("id"), rel["source"], rel["target"]]
            plan["asked_miscon"] = None
            plan["question_no"] += 1
            rdef = _rel_def(topic_def, rel)
            question = rdef.get("probe_question") or GENERIC_REL_QUESTION.format(
                source=rel["source"], target=rel["target"])
            reason = (
                f"The connection between {rel['source']} and {rel['target']} sounded mixed up — checking it."
                if rel["status"] == "contradicted"
                else f"Checking how {rel['source']} and {rel['target']} connect — that link hasn't come up yet."
            )
            return {
                "feedback": feedback,
                "followup": {"kind": "relationship", "text": question,
                             "concept": f"{rel['source']} → {rel['target']}", "reason": reason},
                "done": False,
            }

    rels_ok = all(r["status"] in ("demonstrated", "pending") for r in plan.get("relationships", []))
    all_good = all(e["status"] == "covered" for e in plan["concepts"]) and not plan["detected"] and rels_ok
    extension = topic_def.get("extension_question", "")
    if all_good and extension and not plan["extension_asked"] and plan["question_no"] < MAX_QUESTIONS:
        plan["extension_asked"] = True
        plan["asked_kind"] = "extension"
        plan["asked_miscon"] = None
        plan["question_no"] += 1
        return {
            "feedback": feedback,
            "followup": {
                "kind": "extension",
                "text": extension,
                "concept": None,
                "reason": "Every concept was demonstrated, so here is one stretch question.",
            },
            "done": False,
        }

    plan["done"] = True
    return {"feedback": feedback, "followup": None, "done": True,
            "closing": CLOSING.format(topic=topic_name)}


def play_turn(plan: dict, analysis: dict, topic_def: dict) -> tuple[dict, dict]:
    """Process one student answer. Returns (updated plan, turn result).

    The result dict contains: feedback, followup (None when the questioning is
    over), done, and optionally misconception {name, clarification},
    resolved_misconception, incidental (concept names covered in passing),
    closing.
    """
    plan = {**plan, "concepts": [dict(c) for c in plan["concepts"]],
            "relationships": [dict(r) for r in plan.get("relationships", [])],
            "miscon_seen": list(plan["miscon_seen"]), "resolved": list(plan["resolved"]),
            "detected": list(plan["detected"])}
    plan.setdefault("rel_questions", 0)
    plan.setdefault("asked_rel", None)
    topic_name = topic_def.get("name", "this topic")
    qn = plan["question_no"]
    extras: dict = {}

    # Topic without structured concepts: accept one open explanation and close.
    if not plan["concepts"]:
        plan["done"] = True
        return plan, {"feedback": "Thanks for explaining that.", "followup": None,
                      "done": True, "closing": CLOSING.format(topic=topic_name)}

    incidental = _mark_incidental(plan, analysis)
    if incidental:
        extras["incidental"] = incidental
    # relationship evidence accumulates from every answer, whatever was asked
    _update_relationships(plan, analysis)

    # Hard stop: never exceed the question budget.
    if plan["question_no"] >= MAX_QUESTIONS:
        plan["done"] = True
        result = {"feedback": "Thanks — that gives me a good picture.", "followup": None,
                  "done": True, "closing": CLOSING.format(topic=topic_name), **extras}
        return plan, result

    # --- answering a misconception probe ---
    if plan["asked_kind"] == "misconception" and plan["asked_miscon"]:
        name = plan["asked_miscon"]
        still_detected = name in analysis.get("detected_misconceptions", [])
        cur = plan["concepts"][plan["current"]]
        if not still_detected:
            plan["resolved"].append(name)
            extras["resolved_misconception"] = name
            # credit the current concept from this answer too; explaining the
            # distinction correctly earns at least partial credit
            cur["status"] = "covered" if _verdict(analysis, cur) == "correct" else "partial"
            result = _advance(plan, topic_def, _pick(ACK_RESOLVED, qn))
            return plan, {**result, **extras}
        # still confused: leave the misconception recorded, mark the concept unclear, move on
        cur["status"] = "unclear"
        miscon = next((m for m in topic_def.get("misconceptions", []) if m["name"] == name), None)
        clar = (miscon or {}).get("clarification", "")
        feedback = ("We'll come back to this — for now, keep in mind: " + clar) if clar else \
            "We'll come back to this one later."
        result = _advance(plan, topic_def, feedback)
        return plan, {**result, **extras}

    # --- answering a relationship question ---
    if plan["asked_kind"] == "relationship" and plan["asked_rel"]:
        rid, rsource, rtarget = plan["asked_rel"]
        entry = next(
            (r for r in plan["relationships"]
             if (rid is not None and r.get("id") == rid) or (r["source"] == rsource and r["target"] == rtarget)),
            None,
        )
        plan["asked_rel"] = None
        if entry is not None:
            if entry["status"] == "demonstrated":
                result = _advance(plan, topic_def, _pick(ACK_CORRECT, qn))
                return plan, {**result, **extras}
            rdef = _rel_def(topic_def, entry)
            if entry["status"] == "contradicted":
                feedback = "Careful with that connection — " + (
                    rdef.get("description") or f"think again about how {entry['source']} relates to {entry['target']}."
                )
            else:
                # Asked directly and the connection still was not established.
                # Only an ANSWER THAT ENGAGED with the connection but stopped
                # short of it counts as an incomplete understanding worth
                # clarifying. A blank ("I don't know") or an answer about
                # something else leaves the relationship simply not discussed —
                # absence of evidence is not evidence of a misunderstanding.
                res = _relationship_result(analysis, entry)
                text = " ".join(analysis.get("sentences", [])).lower()
                gave_up = any(ph in text for ph in GIVE_UP_PHRASES)
                if res is not None and res["status"] == "partial" and not gave_up:
                    entry["status"] = "unclear"
                feedback = "That's okay — here's the link: " + (
                    rdef.get("description") or f"{entry['source']} is connected to {entry['target']}."
                ) + " Let's keep going."
            result = _advance(plan, topic_def, feedback)
            return plan, {**result, **extras}

    # --- answering the extension question: no status changes, just close ---
    if plan["asked_kind"] == "extension":
        good = analysis["features"].get("semantic_correctness", 0) >= 0.5
        feedback = "Great answer to a hard question." if good else "Good attempt — that one goes beyond the basics."
        plan["done"] = True
        return plan, {"feedback": feedback, "followup": None, "done": True,
                      "closing": CLOSING.format(topic=topic_name), **extras}

    # --- new misconception detected in a normal answer ---
    fresh = [m for m in analysis.get("misconceptions", [])
             if m.get("detected") and m["name"] not in plan["miscon_seen"]]
    if fresh:
        worst = max(fresh, key=lambda m: m.get("similarity", 0))
        name = worst["name"]
        plan["miscon_seen"].append(name)
        if name not in plan["detected"]:
            plan["detected"].append(name)
        full = next((m for m in topic_def.get("misconceptions", []) if m["name"] == name), {})
        clarification = full.get("clarification", "")
        probe = full.get("probe_question") or "Can you explain that again in your own words?"
        plan["asked_kind"] = "misconception"
        plan["asked_miscon"] = name
        plan["question_no"] += 1
        feedback = "Let's separate two ideas here. " + clarification if clarification else \
            "Let's look at that idea more carefully."
        return plan, {
            "feedback": feedback,
            "followup": {"kind": "misconception", "text": probe, "concept": plan["concepts"][plan["current"]]["name"],
                         "reason": f"A common misconception (\"{name}\") appeared in the answer."},
            "misconception": {"name": name, "clarification": clarification},
            "done": False,
            **extras,
        }

    # --- evaluate the current concept ---
    cur = plan["concepts"][plan["current"]]
    cdef = _concept_def(topic_def, cur)
    # reconstruct the question just asked, to know whether a bare "yes" answers it
    if plan["asked_kind"] in ("main", "easier", "probe"):
        asked = question_for(cdef, plan["asked_kind"], topic_name)
    elif plan["asked_kind"] == "deepen":
        asked = DEEPEN_QUESTION
    else:
        asked = ""
    verdict = _verdict(analysis, cur, confirm_context=_invites_confirmation(asked))

    if verdict == "correct":
        cur["status"] = "covered"
        result = _advance(plan, topic_def, _pick(ACK_CORRECT, qn))
        return plan, {**result, **extras}

    if verdict == "affirm":
        # the deepen follow-up is gated on its own flag, not on the probe
        # attempt counter: the easier yes/no question is usually reached
        # AFTER an unclear attempt, and a correct "yes" there still deserves
        # its "in your own words" follow-up
        if not cur.get("deepened"):
            cur["deepened"] = True
            cur["affirmed"] = True
            plan["asked_kind"] = "deepen"
            plan["question_no"] += 1
            return plan, {
                "feedback": _pick(ACK_AFFIRM, qn),
                "followup": {"kind": "deepen", "text": DEEPEN_QUESTION,
                             "concept": cur["name"],
                             "reason": "The confirmation is a good sign, but agreeing isn't explaining — asking for the idea in the student's own words."},
                "done": False,
                **extras,
            }
        # confirmed again after the deeper follow-up: keep it as partial
        # evidence (they agree with the idea but haven't explained it)
        cur["status"] = "partial"
        result = _advance(plan, topic_def, ACK_AFFIRM_ACCEPT)
        return plan, {**result, **extras}

    if verdict == "analogy":
        if cur["attempts"] == 0:
            cur["attempts"] = 1
            plan["asked_kind"] = "probe"
            plan["question_no"] += 1
            return plan, {
                "feedback": "Interesting analogy — I can see the picture you're drawing.",
                "followup": {"kind": "probe",
                             "text": f"Can you connect that back to {cur['name']} — what does it mean here?",
                             "concept": cur["name"],
                             "reason": "The analogy sounds related, so the student is asked to tie it back to the concept rather than being marked right or wrong."},
                "done": False,
                **extras,
            }
        # a second analogy without the connection stays inconclusive
        cur["status"] = "unclear"
        result = _advance(plan, topic_def, _pick(ACK_MOVE_ON, qn))
        return plan, {**result, **extras}

    if verdict == "partial":
        if cur["attempts"] == 0:
            cur["attempts"] = 1
            plan["asked_kind"] = "probe"
            plan["question_no"] += 1
            return plan, {
                "feedback": _pick(ACK_PARTIAL, qn),
                "followup": {"kind": "probe", "text": question_for(cdef, "probe", topic_name),
                             "concept": cur["name"],
                             "reason": "The answer was partly right, so a targeted follow-up digs one level deeper."},
                "done": False,
                **extras,
            }
        cur["status"] = "partial"
        result = _advance(plan, topic_def, _pick(ACK_ACCEPT_PARTIAL, qn))
        return plan, {**result, **extras}

    # unclear
    if cur["attempts"] == 0:
        cur["attempts"] = 1
        plan["asked_kind"] = "easier"
        plan["question_no"] += 1
        return plan, {
            "feedback": _pick(ACK_UNCLEAR, qn),
            "followup": {"kind": "easier", "text": question_for(cdef, "easier", topic_name),
                         "concept": cur["name"],
                         "reason": "The answer was hard to interpret, so an easier question is asked."},
            "done": False,
            **extras,
        }
    # a concept the student correctly confirmed earlier keeps that positive
    # evidence as partial credit even if the deeper explanation didn't land
    cur["status"] = "partial" if cur.get("affirmed") else "unclear"
    result = _advance(plan, topic_def, _pick(ACK_MOVE_ON, qn))
    return plan, {**result, **extras}


def timeline_out(plan: dict) -> list[dict]:
    """Concept timeline for the UI: done / clarify / current / pending."""
    out = []
    for i, entry in enumerate(plan["concepts"]):
        if entry["status"] == "covered":
            display = "done"
        elif entry["status"] in ("partial", "unclear"):
            display = "clarify"
        elif i == plan["current"] and not plan["done"]:
            display = "current"
        else:
            display = "pending"
        out.append({"name": entry["name"], "status": display})
    return out
