"""Deterministic, template-based follow-up question selection.

No text is generated by a language model. The next prompt is chosen by fixed
rules over the NLP analysis, and filled from teacher-authored templates:

1. Very short / disengaged response  -> restart with a basic question.
2. Misconception detected            -> probe the (strongest) misconception.
3. Required concept missing          -> probe the highest-priority missing concept.
4. Otherwise                         -> extension question for the topic.
"""

LOW_EFFORT_WORDS = 10

GENERIC_BASIC = "Let's start with the basics. In one or two sentences, what problem is {topic} trying to solve?"
GENERIC_CONCEPT_PROBE = "Can you explain what role \"{concept}\" plays in {topic}?"
GENERIC_MISCON_PROBE = (
    "You said something close to: \"{claim}\". Can you think about that again and explain why it is or isn't accurate?"
)
GENERIC_EXTENSION = "Good explanation. Can you give an example of where {topic} is used, or describe one limitation of it?"


def select_followup(analysis: dict, topic_def: dict) -> dict:
    """Pick the next prompt. Returns {kind, text, target} for full explainability."""
    topic_name = topic_def.get("name", "this topic")
    feats = analysis["features"]

    # Rule 1: disengaged / minimal response
    if analysis["word_count"] < LOW_EFFORT_WORDS or feats["response_effort"] < 0.12:
        return {
            "kind": "re_engage",
            "text": GENERIC_BASIC.format(topic=topic_name),
            "target": None,
            "reason": "The response was very short, so the dialogue restarts from a basic question.",
        }

    # Rule 2: strongest detected misconception
    detected = [m for m in analysis["misconceptions"] if m["detected"]]
    if detected:
        worst = max(detected, key=lambda m: m["similarity"])
        full = next(
            (m for m in topic_def.get("misconceptions", []) if m.get("id") == worst["id"] or m["name"] == worst["name"]),
            None,
        )
        text = (full or {}).get("probe_question") or GENERIC_MISCON_PROBE.format(
            claim=(full or {}).get("description", worst["name"])
        )
        return {
            "kind": "misconception_probe",
            "text": text,
            "target": worst["name"],
            "reason": f"A known misconception (\"{worst['name']}\") was detected in the explanation.",
        }

    # Rule 3: first missing required concept (teacher-defined order = priority)
    missing = [c for c in analysis["concepts"] if c["status"] == "missing"]
    if missing:
        target = missing[0]
        full = next(
            (c for c in topic_def.get("concepts", []) if c.get("id") == target["id"] or c["name"] == target["name"]),
            None,
        )
        text = (full or {}).get("probe_question") or GENERIC_CONCEPT_PROBE.format(
            concept=target["name"], topic=topic_name
        )
        return {
            "kind": "concept_probe",
            "text": text,
            "target": target["name"],
            "reason": f"The required concept \"{target['name']}\" was not demonstrated yet.",
        }

    # Rule 4: everything covered -> stretch question
    text = topic_def.get("extension_question") or GENERIC_EXTENSION.format(topic=topic_name)
    return {
        "kind": "extension",
        "text": text,
        "target": None,
        "reason": "All required concepts were demonstrated, so a deeper extension question is asked.",
    }
